# Generated by Django 5.0.3 on 2024-04-03 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Bandworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bandworks_details', models.CharField(max_length=50)),
                ('Bandworks_files', models.FileField(upload_to='workDoc/')),
                ('musicaltype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_musicaltype')),
                ('musicband', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_musicalbandregistration')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_BandGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BandGallery_caption', models.CharField(max_length=50)),
                ('BandGallery_files', models.FileField(upload_to='GalleryDoc/')),
                ('bandwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MusicBand.tbl_bandworks')),
            ],
        ),
    ]
