# Generated by Django 5.0.3 on 2024-04-03 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_MusicalBandRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusicalBandRegistration_name', models.CharField(max_length=50, null=True)),
                ('MusicalBandRegistration_email', models.CharField(max_length=50, null=True)),
                ('MusicalBandRegistration_contact', models.CharField(max_length=50, null=True)),
                ('MusicalBandRegistration_address', models.CharField(max_length=50, null=True)),
                ('MusicalBandRegistration_logo', models.FileField(null=True, upload_to='BandDoc/')),
                ('MusicalBandRegistration_proof', models.FileField(null=True, upload_to='BandDoc/')),
                ('MusicalBandRegistration_password', models.CharField(max_length=50, null=True)),
                ('MusicalBandRegistration_vstatus', models.CharField(default=0, max_length=10)),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_gender', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/UserPhoto/')),
                ('user_proof', models.FileField(upload_to='Assets/UserProof/')),
                ('user_status', models.IntegerField(default='0')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
